name: cascade
channels:
  - conda-forge
dependencies:
  - cmake
  - python
  - heyoka-llvm-13
  - heyoka.py
  - tbb-devel
  - tbb
  - pybind11
  - llvmdev=13.*
  - gcc =10.*
  - gxx =10.*
  - c-compiler
  - cxx-compiler
  - ipython
  - numpy
  - pykep
  - scipy
  - jupyterlab
  - matplotlib
  - ipywidgets
  - tqdm
