name: GitHub CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  conda_asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_conda_asan.sh
  windows_2019:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cascade_devel
          environment-file: cascade_devel.yml
          auto-update-conda: true
          python-version: 3.10
          channels: conda-forge
          channel-priority: strict
          auto-activate-base: false
      - name: Build
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake ../ -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=C:\Miniconda\envs\cascade_devel\Library -DCASCADE_BUILD_TESTS=yes -DBoost_NO_BOOST_CMAKE=ON -DCASCADE_BUILD_PYTHON_BINDINGS=yes
          cmake --build . --config Release --target install
          ctest -j4 -V -C Release
          cd c:\
          python -c "from cascade import test; test.run_test_suite()"
  osx_11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_conda_osx.sh
  build-and-deploydocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Build 🔧 
        run: bash tools/gha_deploydocs.sh
      - name: Upload to github pages 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc/_build/html # The folder the action should deploy.
